apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
      - name: django
        image: your-dockerhub-username/django-docker-k8s:latest  # Replace with your DockerHub image
        ports:
        - containerPort: 8000
        env:
        - name: POSTGRES_DB
          value: "sebastian"
        - name: POSTGRES_USER
          value: "sebastian"
        - name: POSTGRES_PASSWORD
          value: "sebastian"
        - name: POSTGRES_HOST
          value: "postgres-service"  # This should match the PostgreSQL service name
      - name: postgres
        image: postgres:latest
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: "sebastian"
        - name: POSTGRES_USER
          value: "sebastian"
        - name: POSTGRES_PASSWORD
          value: "sebastian"
