name: Django CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # - name: Run tests
    #   run: |
    #     python manage.py test

  #   - name: Log in to Docker Hub
  #     run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

  #   - name: Build Docker image
  #     run: docker build -t your-dockerhub-username/django-docker-k8s:latest .

  #   - name: Push Docker image
  #     run: docker push your-dockerhub-username/django-docker-k8s:latest

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build

  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v2

  #   - name: Set up kubectl
  #     run: |
  #       curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
  #       chmod +x ./kubectl
  #       sudo mv ./kubectl /usr/local/bin/kubectl

  #   - name: Set up Kubeconfig
  #     run: echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config

  #   - name: Deploy to Kubernetes
  #     run: |
  #       kubectl apply -f k8s/deployment.yaml
  #       kubectl apply -f k8s/service.yaml
